{% set version = "2.1.0" %}

package:
  name: shapely
  version: {{ version.split('.post')[0] }}

source:
  url: https://pypi.org/packages/source/S/Shapely/shapely-{{ version }}.tar.gz
  sha256: 2cbe90e86fa8fc3ca8af6ffb00a77b246b918c7cf28677b7c21489b678f6b02e

build:
  number: 0
  skip: true  # [py<310]
  script:
    - set GEOS_INCLUDE_PATH=%LIBRARY_INC%  # [win]
    - set GEOS_LIBRARY_PATH=%LIBRARY_LIB%  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - geos                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython
    - numpy
    - geos
    - setuptools
  run:
    - python

test:
  requires:
    - pytest <8
  imports:
    - shapely
  commands:
    - python -m pytest --pyargs shapely.tests  # [not win]
    # crash on pypy + windows
    - python -m pytest -k "not (test_frechet_distance_densify or test_dump_binary_load_hex)" --pyargs shapely.tests  # [win]

about:
  home: https://github.com/shapely/shapely
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python package for manipulation and analysis of geometric objects in the Cartesian plane

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
    - pelson
    - phobson
    - xylar
    - jorisvandenbossche
    - mwtoews
