{% set version = "1.8.5.post1" %}

package:
  name: shapely
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/Shapely/Shapely-{{ version }}.tar.gz
  sha256: ef3be705c3eac282a28058e6c6e5503419b250f482320df2172abcbea642c831

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - geos                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - shapely
    - shapely.geometry
    - shapely.algorithms
    - shapely.examples
    - shapely.geos

about:
  home: https://github.com/shapely/shapely
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python package for manipulation and analysis of geometric objects in the Cartesian plane

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
    - pelson
    - phobson
    - xylar
    - jorisvandenbossche
    - mwtoews
