{% set version = "1.8.0" %}

package:
  name: shapely
  version: {{ version.split('.post')[0] }}

source:
  url: https://pypi.io/packages/source/S/Shapely/Shapely-{{ version }}.tar.gz
  sha256: f5307ee14ba4199f8bbcf6532ca33064661c1433960c432c84f0daa73b47ef9c

build:
  number: 3
  # tests are failing for osx and py 3.10
  # see https://github.com/Toblerity/Shapely/issues/1227
  skip: True  # [osx and py>39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - geos                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - shapely
    - shapely.geometry
    - shapely.algorithms
    - shapely.examples
    - shapely.geos

about:
  home: https://github.com/Toblerity/Shapely
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python package for manipulation and analysis of geometric objects in the Cartesian plane

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - phobson
    - xylar
    - jorisvandenbossche
