{% set version = "2.0b1" %}

package:
  name: shapely
  version: {{ version.split('.post')[0] }}

source:
  url: https://pypi.io/packages/source/S/Shapely/shapely-{{ version }}.tar.gz
  sha256: 624dce6c1bcff6f461fc3ce45f6477baa71754b46fcdca40d481b9a3573c871d

build:
  number: 0
  skip: True  # [python_impl == 'pypy']
  script:
    - set GEOS_INCLUDE_PATH=%LIBRARY_INC%  # [win]
    - set GEOS_LIBRARY_PATH=%LIBRARY_LIB%  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - geos                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - shapely
    - shapely.geometry
    - shapely.algorithms
    - shapely.examples
    - shapely.geos
  commands:
  # test_setattr_disallowed fails on pypy
  # (TODO skip this test automatically in Shapely for pypy)
    - pytest --pyargs shapely.tests -k "not test_setattr_disallowed"

about:
  home: https://github.com/shapely/shapely
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python package for manipulation and analysis of geometric objects in the Cartesian plane

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
    - pelson
    - phobson
    - xylar
    - jorisvandenbossche
    - mwtoews
