{% set version = "2.0.0" %}

package:
  name: shapely
  version: {{ version.split('.post')[0] }}

source:
  url: https://pypi.io/packages/source/S/Shapely/shapely-{{ version }}.tar.gz
  sha256: 11f1b1231a6c04213fb1226c6968d1b1b3b369ec42d1e9655066af87631860ea

build:
  number: 0
  script:
    - set GEOS_INCLUDE_PATH=%LIBRARY_INC%  # [win]
    - set GEOS_LIBRARY_PATH=%LIBRARY_LIB%  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - geos                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - shapely
  commands:
    - pytest --pyargs shapely.tests

about:
  home: https://github.com/shapely/shapely
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python package for manipulation and analysis of geometric objects in the Cartesian plane

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
    - pelson
    - phobson
    - xylar
    - jorisvandenbossche
    - mwtoews
