{% set version = "2.0.1" %}

package:
  name: shapely
  version: {{ version.split('.post')[0] }}

source:
  url: https://pypi.io/packages/source/S/Shapely/shapely-{{ version }}.tar.gz
  sha256: 66a6b1a3e72ece97fc85536a281476f9b7794de2e646ca8a4517e2e3c1446893

build:
  number: 3
  script:
    - set GEOS_INCLUDE_PATH=%LIBRARY_INC%  # [win]
    - set GEOS_LIBRARY_PATH=%LIBRARY_LIB%  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - geos                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython <3
    - numpy
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - shapely
  commands:
    # geos 3.12 tests skipped until next release
    {% set tests_to_skip = "test_coverage_union_overlapping_inputs" %}
    {% set tests_to_skip = tests_to_skip + " or test_coverage_union_non_polygon_inputs" %}
    {% set tests_to_skip = tests_to_skip + " or test_to_wkt_multipoint_with_point_empty" %}
    {% set tests_to_skip = tests_to_skip + " or test_minimum_rotated_rectangle" %}
    {% set tests_to_skip = tests_to_skip + " or test_oriented_envelope" %}
    - python -m pytest -k "not ({{ tests_to_skip }})" --pyargs shapely.tests

about:
  home: https://github.com/shapely/shapely
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python package for manipulation and analysis of geometric objects in the Cartesian plane

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
    - pelson
    - phobson
    - xylar
    - jorisvandenbossche
    - mwtoews
