# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangpython2.7
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython2.7
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gILRa9BUf7GMmnB7tQ1/1iEkQEcar7z6AHHYYgjEz3rJMclyIQ4ohMdA+jFKEKt1tcmepcBgtxSmYkSjSpRZW0vdmjO5phtaKm4VudLW6XUToWyFLKntdvaJRNXQapYUROkTZuDtNQrLYqNkQRBDtWZ5dUvdJfRWKHjYSxt2UvWpHSKCuY1ME6/3pFdTliV2l3Xxx+jasRewHe1YG03ih6eSHKsXV4NZnWryhvxUfhKzqK/Ob6/AG+AL7CYUsTVDiWjoLS7yY7fWBE9ptudDp7j0wHMWwJRCWYDC3XnOzT3fRRZMrJqy4nE2cdob4FGnkRO800PVInSQ8zawxYkrvvWD/yBPhsQsKUb1108bGiOrWqVlcUHc7fr7WcEMMBaLB1iIoAkrYRKYALN4OHQRBHe8LxyNO8Ct8wmvsobTeDMeRcmH9Ur63O57zDgufhwDUN6sOBDGSj9L/w6tAfyy+Xbgib9zacYqkDHgdprUG2fjb6CmV3ubSsbuHn4gP9+xudWzYpmUHJ5QZ27KxRLRYAnM3aE6gNAs6ajbrMUgmWHxs+7bD4GL5vl6IOx4TlR2/rm7VZLNlI5mq4c3WzXfYhsiRC+Qqo69lnZszdntq9guoeOPzc45y0Xhg6ZYkZS+WNCY+c+E1akOs1bpp/i50av6wwEallKRwsvabiiJiBo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
