appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gILRa9BUf7GMmnB7tQ1/1iEkQEcar7z6AHHYYgjEz3rJMclyIQ4ohMdA+jFKEKt1tcmepcBgtxSmYkSjSpRZW0vdmjO5phtaKm4VudLW6XUToWyFLKntdvaJRNXQapYUROkTZuDtNQrLYqNkQRBDtWZ5dUvdJfRWKHjYSxt2UvWpHSKCuY1ME6/3pFdTliV2l3Xxx+jasRewHe1YG03ih6eSHKsXV4NZnWryhvxUfhKzqK/Ob6/AG+AL7CYUsTVDiWjoLS7yY7fWBE9ptudDp7j0wHMWwJRCWYDC3XnOzT3fRRZMrJqy4nE2cdob4FGnkRO800PVInSQ8zawxYkrvvWD/yBPhsQsKUb1108bGiOrWqVlcUHc7fr7WcEMMBaLB1iIoAkrYRKYALN4OHQRBHe8LxyNO8Ct8wmvsobTeDMeRcmH9Ur63O57zDgufhwDUN6sOBDGSj9L/w6tAfyy+Xbgib9zacYqkDHgdprUG2fjb6CmV3ubSsbuHn4gP9+xudWzYpmUHJ5QZ27KxRLRYAnM3aE6gNAs6ajbrMUgmWHxs+7bD4GL5vl6IOx4TlR2/rm7VZLNlI5mq4c3WzXfYhsiRC+Qqo69lnZszdntq9guoeOPzc45y0Xhg6ZYkZS+WNCY+c+E1akOs1bpp/i50av6wwEallKRwsvabiiJiBo=}
